apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "mongodb.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount | len }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "mongodb.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "mongodb.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: MONGO_PATH_CONFIG_FILE
              value: {{ .Values.application.config | default "/etc/mongodb/mongod.conf" }}
          volumeMounts:
            - name: mongo-data
              mountPath: /var/lib/mongodb
            - name: mongo-config
              mountPath: /etc/mongodb
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.livenessProbe.tcpSocket.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
      volumes:
        - name: mongo-config
          configMap:
            name: {{ .Release.Name }}
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        {{- if .Values.storage.className}}
        storageClassName: {{ .Values.storage.className }}
        {{- end}}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage.size }}
