# Default values for rabbitmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  - 0

storage:
  # className: managed-nfs-storage
  size: 5Gi

livenessProbe:
  tcpSocket:
    port: 5672

image:
  repository: rabbitmq
  tag: 3.6-management-alpine
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
    - name: http
      protocol: TCP
      port: 15672
      targetPort: http

resources:
  limits:
    memory: 10Gi

nodeSelector: {}

tolerations: []

affinity: {}
