# Default values for mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  # config: /etc/mongodb/mongod.conf
  cacheSizeGB: 5

replicaCount:
  - 0

storage:
  # className: managed-nfs-storage
  size: 5Gi

livenessProbe:
  tcpSocket:
    port: 27017

image:
  repository: mongo
  tag: 3.4
  pullPolicy: Always

service:
  name: mongodb
  type: ClusterIP
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: http

resources:
  limits:
    memory: 5Gi

nodeSelector: {}

tolerations: []

affinity: {}
