apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ template "consul.fullname" . }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "consul.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ template "consul.name" . }}
  replicas: {{ .Values.replicaCount | len }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "consul.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ template "consul.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSUL_UI_BETA
              value: "true"
          args:
            {{- $serviceName := .Values.service.name }}
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bind=0.0.0.0"
            - "-bootstrap-expect={{ .Values.replicaCount | len }}"
            {{- range $i, .Values.replicaCount }}
            - "-retry-join={{ $serviceName }}-{{ $i }}.{{ $serviceName }}.$(NAMESPACE).svc.cluster.local"
            {{- end }}
            - "-client=0.0.0.0"
            - "-datacenter={{ .Values.consul.datacenter | default 'dc1' }}"
            - "-data-dir=/consul/data"
            - "-domain=cluster.local"
            - "-server"
            - "-ui"
            - "-disable-host-node-id"
          volumeMounts:
            - name: consul-data
              mountPath: /consul/data
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - consul leave
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.livenessProbe.tcpSocket.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: consul-data
      spec:
        {{- if .Values.storage.className}}
        storageClassName: {{ .Values.storage.className }}
        {{- end}}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage.size }}
